// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47_xWOhUTV7PDaJKwwVCGQUXaY_KFL0w',
    appId: '1:1035494837242:web:6081de87f24f7288327243',
    messagingSenderId: '1035494837242',
    projectId: 'tiktok-yt-ff3cd',
    authDomain: 'tiktok-yt-ff3cd.firebaseapp.com',
    storageBucket: 'tiktok-yt-ff3cd.appspot.com',
    measurementId: 'G-SDB5898SXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMb7QLBInVyqlN5RhUN36fB0n7TEwPyNI',
    appId: '1:1035494837242:android:07e37ec5d485a522327243',
    messagingSenderId: '1035494837242',
    projectId: 'tiktok-yt-ff3cd',
    storageBucket: 'tiktok-yt-ff3cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lM7Xo1MzNxrp2gvKVw4xDctWosFsxcM',
    appId: '1:1035494837242:ios:16dbe36960b9101e327243',
    messagingSenderId: '1035494837242',
    projectId: 'tiktok-yt-ff3cd',
    storageBucket: 'tiktok-yt-ff3cd.appspot.com',
    iosClientId: '1035494837242-3om9djv773afqbas86hrcc6p4ro352cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8lM7Xo1MzNxrp2gvKVw4xDctWosFsxcM',
    appId: '1:1035494837242:ios:16dbe36960b9101e327243',
    messagingSenderId: '1035494837242',
    projectId: 'tiktok-yt-ff3cd',
    storageBucket: 'tiktok-yt-ff3cd.appspot.com',
    iosClientId: '1035494837242-3om9djv773afqbas86hrcc6p4ro352cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
